import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Header from "@components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="keywords"
          content="Amron Real estate, Property sale, Property buy "
        />
        <meta
          name="description"
          content="Amron is a Real Estate  and Contruction Agency."
        />
        <meta property="og:site_name" content="Homy" />
        <meta property="og:url" content="https://creativegigstf.com/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Amron Real Estate " />
        <meta name="og:image" content="/images/assets/ogg.png" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#0D1A1C" />
        <meta name="msapplication-navbutton-color" content="#0D1A1C" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#0D1A1C" />
        <title>Amron Real Estate </title>
        <link
          rel="icon"
          type="image/png"
          sizes="56x56"
          href="/images/fav-icon/icon.png"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/css/bootstrap.min.css"
          media="all"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/css/style.min.css"
          media="all"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="/css/responsive.css"
          media="all"
        />
      </head>

      <body className={inter.className}>
        <Header />
        {children}
        <div
          className="modal fade"
          id="loginModal"
          tabIndex={-1}
          aria-hidden="true"
        >
          <div className="modal-dialog modal-fullscreen modal-dialog-centered">
            <div className="container">
              <div className="user-data-form modal-content">
                <button
                  type="button"
                  className="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
                <div className="form-wrapper m-auto">
                  <ul className="nav nav-tabs w-100" role="tablist">
                    <li className="nav-item" role="presentation">
                      <button
                        className="nav-link active"
                        data-bs-toggle="tab"
                        data-bs-target="#fc1"
                        role="tab"
                      >
                        Login
                      </button>
                    </li>
                    <li className="nav-item" role="presentation">
                      <button
                        className="nav-link"
                        data-bs-toggle="tab"
                        data-bs-target="#fc2"
                        role="tab"
                      >
                        Signup
                      </button>
                    </li>
                  </ul>
                  <div className="tab-content mt-30">
                    <div
                      className="tab-pane show active"
                      role="tabpanel"
                      id="fc1"
                    >
                      <div className="text-center mb-20">
                        <h2>Welcome Back!</h2>
                        <p className="fs-20 color-dark">
                          Still dont have an account? <a href="#">Sign up</a>
                        </p>
                      </div>
                      <form action="#">
                        <div className="row">
                          <div className="col-12">
                            <div className="input-group-meta position-relative mb-25">
                              <label>Email*</label>
                              <input
                                type="email"
                                placeholder="Youremail@gmail.com"
                              />
                            </div>
                          </div>
                          <div className="col-12">
                            <div className="input-group-meta position-relative mb-20">
                              <label>Password*</label>
                              <input
                                type="password"
                                placeholder="Enter Password"
                                className="pass_log_id"
                              />
                              <span className="placeholder_icon">
                                <span className="passVicon">
                                  <img src="images/icon/icon_68.svg" alt="" />
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="col-12">
                            <div className="agreement-checkbox d-flex justify-content-between align-items-center">
                              <div>
                                <input type="checkbox" id="remember" />
                                <label htmlFor="remember">
                                  Keep me logged in
                                </label>
                              </div>
                              <a href="#">Forget Password?</a>
                            </div>
                          </div>
                          <div className="col-12">
                            <button className="btn-two w-100 text-uppercase d-block mt-20">
                              Login
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                    <div className="tab-pane" role="tabpanel" id="fc2">
                      <div className="text-center mb-20">
                        <h2>Register</h2>
                        <p className="fs-20 color-dark">
                          Already have an account? <a href="#">Login</a>
                        </p>
                      </div>
                      <form action="#">
                        <div className="row">
                          <div className="col-12">
                            <div className="input-group-meta position-relative mb-25">
                              <label>Name*</label>
                              <input type="text" placeholder="Zubayer Hasan" />
                            </div>
                          </div>
                          <div className="col-12">
                            <div className="input-group-meta position-relative mb-25">
                              <label>Email*</label>
                              <input
                                type="email"
                                placeholder="zubayerhasan@gmail.com"
                              />
                            </div>
                          </div>
                          <div className="col-12">
                            <div className="input-group-meta position-relative mb-20">
                              <label>Password*</label>
                              <input
                                type="password"
                                placeholder="Enter Password"
                                className="pass_log_id"
                              />
                              <span className="placeholder_icon">
                                <span className="passVicon">
                                  <img src="images/icon/icon_68.svg" alt="" />
                                </span>
                              </span>
                            </div>
                          </div>
                          <div className="col-12">
                            <div className="agreement-checkbox d-flex justify-content-between align-items-center">
                              <div>
                                <input type="checkbox" id="remember2" />
                                <label htmlFor="remember2">
                                  By hitting the Register button, you agree to
                                  the <a href="#">Terms conditions</a> &
                                  <a href="#">Privacy Policy</a>
                                </label>
                              </div>
                            </div>
                          </div>
                          <div className="col-12">
                            <button className="btn-two w-100 text-uppercase d-block mt-20">
                              Sign Up
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>

                  <div className="d-flex align-items-center mt-30 mb-10">
                    <div className="line"></div>
                    <span className="pe-3 ps-3 fs-6">OR</span>
                    <div className="line"></div>
                  </div>
                  <div className="row">
                    <div className="col-sm-6">
                      <a
                        href="#"
                        className="social-use-btn d-flex align-items-center justify-content-center tran3s w-100 mt-10"
                      >
                        <img src="images/icon/google.png" alt="" />
                        <span className="ps-3">Signup with Google</span>
                      </a>
                    </div>
                    <div className="col-sm-6">
                      <a
                        href="#"
                        className="social-use-btn d-flex align-items-center justify-content-center tran3s w-100 mt-10"
                      >
                        <img src="images/icon/facebook.png" alt="" />
                        <span className="ps-3">Signup with Facebook</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
        <button className="scroll-top">
          <i className="bi bi-arrow-up-short"></i>
        </button>
        <Script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" />
        <Script src="/vendor/html5shiv.js" />
        <Script src="/vendor/respond.js" />
        <Script src="/vendor/jquery.min.js" />
        <Script src="/vendor/bootstrap/js/bootstrap.bundle.min.js" />
        <Script src="/vendor/wow/wow.min.js" />
        <Script src="/vendor/slick/slick.min.js" />
        <Script src="/vendor/fancybox/fancybox.umd.js" />
        <Script src="/vendor/jquery.lazy.min.js" />
        <Script src="/vendor/jquery.counterup.min.js" />
        <Script src="/vendor/jquery.waypoints.min.js" />
        <Script src="/vendor/nice-select/jquery.nice-select.min.js" />
        <Script src="/vendor/validator.js" />

        <Script src="/js/theme.js" />
      </body>
    </html>
  );
}
